plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'solo'
version = '0.0.1-ALPHA'
description = 'PixelMonitor'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

repositories {
    mavenCentral()
}


javafx {
    version = "26.0.2"
    modules = [ 'javafx.controls', 'javafx.swing' ]
}

configurations {
    mockitoAgent {
        transitive = false
    }
}

dependencies {
    implementation("org.controlsfx:controlsfx:11.2.4")
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation("com.github.kwhat:jnativehook:2.2.2")
    implementation 'io.github.mkpaz:atlantafx-base:2.1.0'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
    mockitoAgent platform('org.springframework.boot:spring-boot-dependencies:4.1.0')
    mockitoAgent 'org.mockito:mockito-core'
}

tasks.named('test') {
    useJUnitPlatform()
    jvmArgs "-javaagent:${configurations.mockitoAgent.asPath}"
}
